
import React from 'react';
import { Profile, Review, Language } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'p1',
    name: 'Elvin Məmmədov',
    role: 'PROFESSIONAL',
    profession: 'Santexnik',
    skills: ['Santexnik', 'Təmir', 'Boru təmiri'],
    bio: '10 ildən çox təcrübəli santexnik ustasıyam. Hər növ boru və kran təmirini yüksək keyfiyyətlə yerinə yetirirəm.',
    hourlyRate: 25,
    rating: 4.8,
    reviewsCount: 42,
    avatar: 'https://picsum.photos/id/1012/200/200',
    location: 'Bakı, Nərimanov',
    availability: ['Bazar ertəsi', 'Çərşənbə', 'Cümə'],
    joinedDate: '2023-01-15',
    onboarding_completed: true
  }
];

export const I18N = {
  az: {
    heroTitle: "Eviniz üçün ən yaxşı köməkçiləri tapın",
    heroSubtitle: "Peşəkar santexniklər, elektriklər və təmizlikçilər bir klik uzaqlığında.",
    searchPlaceholder: "Nə xidmət lazımdır? (məs: santexnik, təmizlik)",
    popularCategories: "Populyar Kateqoriyalar",
    plumbing: "Santexnik",
    cleaning: "Təmizlik",
    electrician: "Elektrik",
    renovation: "Təmir",
    searchBtn: "Axtar",
    hourlyRate: "Saatlıq tarif",
    viewProfile: "Profilə bax",
    makeOffer: "Təklif et",
    myOffers: "Sifarişlərim",
    becomePro: "Usta ol",
    login: "Giriş",
    home: "Ana səhifə",
    azn: "AZN",
    editProfile: "Profili redaktə et",
    saveChanges: "Yadda saxla",
    nameLabel: "Ad və Soyad",
    bioLabel: "Bioqrafiya",
    professionLabel: "Peşə",
    avatarLabel: "Profil şəkli URL",
    hourlyRateLabel: "Saatlıq tarif (10-100 AZN)",
    successUpdate: "Profil uğurla yeniləndi!",
    cancel: "Ləğv et",
    loginBtn: "Daxil ol",
    signupBtn: "Hesab yarat",
    emailLabel: "E-poçt ünvanı",
    passwordLabel: "Şifrə",
    authTitleLogin: "Giriş",
    authTitleSignup: "Qeydiyyat",
    selectAccountType: "Zəhmət olmasa hesab növünü seçin",
    customerRole: "Müştəri",
    proRole: "Mütəxəssis",
    noAccount: "Hesabınız yoxdur?",
    hasAccount: "Artıq hesabınız var?",
    panel: "Panel",
    incomingOffers: "Gələn təkliflər",
    myRequests: "Mənim müraciətlərim",
    status: "Status",
    locationLabel: "Məkan",
    jobDesc: "İşin təsviri",
    dateLabel: "Tarix",
    timeLabel: "Vaxt",
    addressLabel: "Ünvan",
    noActivity: "Hələ ki heç bir aktivlik yoxdur.",
    noProsFound: "Usta tapılmadı",
    noProsFoundSub: "Axtarış sözünü dəyişməyə və ya başqa kateqoriyaya baxmağa çalışın.",
    geminiSearching: "Gemini ağıllı axtarış edir...",
    send: "Göndər",
    security: "Təhlükəsizlik",
    details: "Detallar",
    accept: "Qəbul et",
    decline: "İmtina",
    verifyEmailTitle: "E-poçtunuzu yoxlayın",
    verifyEmailDesc: "Qeydiyyatı tamamlamaq üçün e-poçtunuza göndərdiyimiz təsdiq linkinə klikləyin.",
    onboardingTitle: "Profilinizi quraşdırın",
    onboardingStep1: "Şəkil yükləyin",
    onboardingStep2: "Məlumatları daxil edin",
    completeOnboarding: "Tamamla",
    uploadPhoto: "Şəkil yüklə",
    bioMinLength: "Bioqrafiya ən azı 50 simvol olmalıdır",
    photoRequired: "Usta profili üçün şəkil mütləqdir",
    cityLabel: "Şəhər / Region",
    next: "Növbəti"
  },
  en: {
    heroTitle: "Find the best helpers for your home",
    heroSubtitle: "Professional plumbers, electricians, and cleaners are just a click away.",
    searchPlaceholder: "What service do you need? (e.g., plumber, cleaning)",
    popularCategories: "Popular Categories",
    plumbing: "Plumbing",
    cleaning: "Cleaning",
    electrician: "Electrician",
    renovation: "Renovation",
    searchBtn: "Search",
    hourlyRate: "Hourly rate",
    viewProfile: "View Profile",
    makeOffer: "Make Offer",
    myOffers: "My Offers",
    becomePro: "Become Professional",
    login: "Login",
    home: "Home",
    azn: "AZN",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    nameLabel: "Full Name",
    bioLabel: "Biography",
    professionLabel: "Profession",
    avatarLabel: "Profile Picture URL",
    hourlyRateLabel: "Hourly Rate (10-100 AZN)",
    successUpdate: "Profile updated successfully!",
    cancel: "Cancel",
    loginBtn: "Login",
    signupBtn: "Create Account",
    emailLabel: "Email address",
    passwordLabel: "Password",
    authTitleLogin: "Login",
    authTitleSignup: "Sign Up",
    selectAccountType: "Please select your account type",
    customerRole: "Customer",
    proRole: "Professional",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    panel: "Panel",
    incomingOffers: "Incoming Offers",
    myRequests: "My Requests",
    status: "Status",
    locationLabel: "Location",
    jobDesc: "Job Description",
    dateLabel: "Date",
    timeLabel: "Time",
    addressLabel: "Address",
    noActivity: "No activity yet.",
    noProsFound: "No experts found",
    noProsFoundSub: "Try changing the search term or looking at another category.",
    geminiSearching: "Gemini is performing a smart search...",
    send: "Send",
    security: "Security",
    details: "Details",
    accept: "Accept",
    decline: "Decline",
    verifyEmailTitle: "Verify your email",
    verifyEmailDesc: "Please check your inbox and click the verification link to complete registration.",
    onboardingTitle: "Set up your profile",
    onboardingStep1: "Upload Photo",
    onboardingStep2: "Enter Details",
    completeOnboarding: "Complete",
    uploadPhoto: "Upload Photo",
    bioMinLength: "Bio must be at least 50 characters",
    photoRequired: "A profile photo is mandatory for professionals",
    cityLabel: "City / Region",
    next: "Next"
  },
  ru: {
    heroTitle: "Найдите лучших помощников для вашего дома",
    heroSubtitle: "Профессиональные сантехники, электрики и уборщики на расстоянии одного клика.",
    searchPlaceholder: "Какая услуга вам нужна? (напр: сантехник, уборка)",
    popularCategories: "Популярные Категории",
    plumbing: "Сантехник",
    cleaning: "Уборка",
    electrician: "Электрик",
    renovation: "Ремонт",
    searchBtn: "Поиск",
    hourlyRate: "Почасовая ставка",
    viewProfile: "Профиль",
    makeOffer: "Предложить",
    myOffers: "Мои заказы",
    becomePro: "Стать мастером",
    login: "Вход",
    home: "Главная",
    azn: "AZN",
    editProfile: "Редактировать профиль",
    saveChanges: "Сохранить",
    nameLabel: "Имя и Фамилия",
    bioLabel: "Биография",
    professionLabel: "Профессия",
    avatarLabel: "URL аватара",
    hourlyRateLabel: "Почасовая ставка (10-100 AZN)",
    successUpdate: "Профиль успешно обновлен!",
    cancel: "Отмена",
    loginBtn: "Войти",
    signupBtn: "Создать аккаунт",
    emailLabel: "Эл. почта",
    passwordLabel: "Пароль",
    authTitleLogin: "Вход",
    authTitleSignup: "Регистрация",
    selectAccountType: "Пожалуйста, выберите тип аккаунта",
    customerRole: "Клиент",
    proRole: "Профессионал",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже есть аккаунт?",
    panel: "Панель",
    incomingOffers: "Входящие предложения",
    myRequests: "Мои запросы",
    status: "Статус",
    locationLabel: "Местоположение",
    jobDesc: "Описание работы",
    dateLabel: "Дата",
    timeLabel: "Время",
    addressLabel: "Адрес",
    noActivity: "Пока нет активности.",
    noProsFound: "Мастера не найдены",
    noProsFoundSub: "Попробуйте изменить поисковый запрос или посмотреть другую категорию.",
    geminiSearching: "Gemini выполняет умный поиск...",
    send: "Отправить",
    security: "Безопасность",
    details: "Детали",
    accept: "Принять",
    decline: "Отказать",
    verifyEmailTitle: "Подтвердите email",
    verifyEmailDesc: "Пожалуйста, проверьте почту и перейдите по ссылке для завершения регистрации.",
    onboardingTitle: "Настройте ваш профиль",
    onboardingStep1: "Загрузить фото",
    onboardingStep2: "Введите данные",
    completeOnboarding: "Завершить",
    uploadPhoto: "Загрузить фото",
    bioMinLength: "Биография должна быть не менее 50 символов",
    photoRequired: "Фото профиля обязательно для профессионалов",
    cityLabel: "Город / Регион",
    next: "Далее"
  }
};
