
import React from 'react';
import { Profile, Language } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'p1',
    name: 'Elvin Məmmədov',
    role: 'PROFESSIONAL',
    profession: 'Santexnik',
    skills: ['Santexnik', 'Təmir', 'Boru təmiri'],
    bio: '10 ildən çox təcrübəli santexnik ustasıyam. Hər növ boru və kran təmirini yüksək keyfiyyətlə yerinə yetirirəm.',
    hourlyRate: 25,
    rating: 4.8,
    reviewsCount: 42,
    avatar: 'https://images.unsplash.com/photo-1540560340339-44432095813d?auto=format&fit=crop&q=80&w=200&h=200',
    location: 'Bakı, Nərimanov',
    availability: ['Bazar ertəsi', 'Çərşənbə', 'Cümə'],
    joinedDate: '2023-01-15',
    onboarding_completed: true,
    isAvailable: true
  }
];

export const PROFESSION_OPTIONS = {
  az: ["Santexnik", "Elektrik", "Təmizlikçi", "Kombi Ustası", "Malyar", "Bənna", "Dərzi", "Dayə", "Bağban", "Kuryer", "Digər"],
  en: ["Plumber", "Electrician", "Cleaner", "Boiler Technician", "Painter", "Mason", "Tailor", "Nanny", "Gardener", "Courier", "Other"],
  ru: ["Сантехник", "Электрик", "Уборщик", "Мастер по котлам", "Маляр", "Каменщик", "Портной", "Няня", "Садовник", "Курьер", "Другое"]
};

export const I18N = {
  az: {
    heroTitle: "Eviniz üçün peşəkar köməkçilər",
    heroSubtitle: "Bakının ən yaxşı ustaları bir platformada. Təhlükəsiz ödəniş və zəmanətli xidmət.",
    searchPlaceholder: "Hansı xidmətə ehtiyacınız var? (məs: kombi təmiri, təmizlik)",
    popularCategories: "Populyar Xidmətlər",
    searchBtn: "Axtar",
    hourlyRate: "Saatlıq tarif",
    viewProfile: "Profilə bax",
    makeOffer: "Sifariş et",
    myOffers: "Sifarişlərim",
    becomePro: "Usta ol",
    login: "Daxil ol",
    home: "Ana səhifə",
    azn: "AZN",
    editProfile: "Profili redaktə et",
    saveChanges: "Yadda saxla",
    nameLabel: "Ad və Soyad",
    bioLabel: "Peşəkar Bioqrafiya",
    professionLabel: "Peşəniz",
    avatarLabel: "Profil şəkli",
    hourlyRateLabel: "Saatlıq tarif (10-100 AZN)",
    successUpdate: "Profil uğurla yeniləndi!",
    cancel: "Ləğv et",
    loginBtn: "Daxil ol",
    signupBtn: "Qeydiyyatdan keç",
    emailLabel: "E-poçt ünvanı",
    passwordLabel: "Şifrə",
    authTitleLogin: "Xoş gəlmisiniz",
    authTitleSignup: "Platformaya qoşulun",
    selectAccountType: "Hesab növünü seçin",
    customerRole: "Müştəri",
    proRole: "Usta",
    noAccount: "Hesabınız yoxdur?",
    hasAccount: "Artıq qeydiyyatdan keçmisiniz?",
    panel: "İdarə Paneli",
    incomingOffers: "Yeni Sifarişlər",
    myRequests: "Mənim Sifarişlərim",
    status: "Status",
    locationLabel: "Ünvan",
    jobDesc: "İşin təsviri",
    dateLabel: "Tarix",
    timeLabel: "Vaxt",
    addressLabel: "Tam ünvan",
    noActivity: "Hələ ki heç bir fəaliyyət yoxdur.",
    noProsFound: "Nəticə tapılmadı",
    noProsFoundSub: "Axtarış sözlərini dəyişərək yenidən yoxlayın.",
    geminiSearching: "AI mütəxəssis axtarır...",
    send: "Sifarişi göndər",
    security: "Təhlükəsizlik",
    details: "Detallar",
    accept: "Qəbul et",
    decline: "İmtina et",
    verifyEmailTitle: "E-poçtu təsdiqləyin",
    verifyEmailDesc: "Qeydiyyatı tamamlamaq üçün e-poçtunuza göndərilən linkə keçid edin.",
    onboardingTitle: "Profilinizi tamamlayın",
    onboardingStep1: "Şəkil",
    onboardingStep2: "Detallar",
    completeOnboarding: "Profilimi aç",
    uploadPhoto: "Şəkil seçin",
    bioMinLength: "Təcrübəniz haqqında bir az yazın",
    photoRequired: "Usta olmaq üçün şəkil mütləqdir",
    cityLabel: "Şəhər",
    next: "Davam et",
    activeJobs: "Aktiv və Gözləyən",
    completedJobs: "Tamamlananlar",
    profileViews: "Baxış sayı",
    quickActions: "Sürətli Əməliyyatlar",
    availabilityText: "Hal-hazırda sifariş qəbul edirəm",
    notAvailableText: "Məşğulam / Sifariş qəbul edilmir",
    otherProfession: "Digər (Zəhmət olmasa yazın)",
    refresh: "Yenilə",
    pending: "Gözləmədə",
    accepted: "Qəbul edildi",
    declined: "İmtina edildi",
    completed: "Tamamlandı",
    pay: "Ödəniş Et",
    paid: "Ödənilib",
    checkoutTitle: "Təhlükəsiz Ödəniş",
    cardNumber: "Kart nömrəsi",
    expiry: "MM/İİ",
    cvc: "CVC",
    payNow: "İndi ödə",
    secureCheckout: "Bank səviyyəli təhlükəsizlik",
    paymentSuccess: "Ödəniş uğurla tamamlandı!",
    summary: "Xülasə",
    serviceFee: "Xidmət haqqı",
    totalAmount: "Yekun məbləğ",
    verified: "Təsdiqlənib",
    unverified: "Təsdiqlənməyib",
    securityAudit: "Təhlükəsizlik Auditi",
    pciCompliance: "PCI Uyğunluğu",
    pciDesc: "Kart məlumatlarınız heç vaxt Helper.az bazasında saxlanılmır.",
    safetyGuarantee: "100% Təhlükəsizlik Zəmanəti",
    safetyDesc: "Mütəxəssislərimiz ciddi seçim və yoxlama mərhələsindən keçirlər.",
    howItWorks: "Necə işləyir?",
    whyUs: "Niyə biz?",
    contact: "Əlaqə",
    step1Title: "Xidməti Axtarın",
    step1Desc: "Ehtiyacınız olan xidməti AI axtarış sistemimizlə asanlıqla tapın.",
    step2Title: "Ustanı Seçin",
    step2Desc: "Reytinq və şərhlərə baxaraq ən yaxşı mütəxəssisi sifariş edin.",
    step3Title: "Təhlükəsiz Ödəyin",
    step3Desc: "İş tamamlandıqdan sonra ödənişi təhlükəsiz şəkildə edin.",
    whyUs1Title: "Yoxlanılmış Ustalar",
    whyUs1Desc: "Hər bir usta şəxsiyyət vəsiqəsi ilə yoxlanılır.",
    whyUs2Title: "Fiks Qiymət",
    whyUs2Desc: "Qiymətlər əvvəlcədən bəllidir, gizli xərclər yoxdur.",
    whyUs3Title: "24/7 Dəstək",
    whyUs3Desc: "Hər hansı bir çətinlikdə bizimlə əlaqə saxlaya bilərsiniz.",
    contactTitle: "Bizimlə Əlaqə",
    contactSubtitle: "Sualınız var? Bizə yazın.",
    sendMessage: "Mesaj göndər",
    messageLabel: "Mesajınız",
    footerAbout: "Helper.az Bakıda ən etibarlı xidmət bazarıdır.",
    rights: "Bütün hüquqlar qorunur.",
    // New
    emailVerifiedTitle: "E-poçt Təsdiqləndi!",
    emailVerifiedDesc: "Təbriklər! Hesabınız uğurla aktivləşdirildi. İndi daxil olaraq xidmətlərdən istifadə edə bilərsiniz.",
    goToLogin: "Giriş Səhifəsinə Get"
  },
  en: {
    heroTitle: "Professional Helpers for Your Home",
    heroSubtitle: "Top experts in Baku on one platform. Secure payments and guaranteed service.",
    searchPlaceholder: "What service do you need? (e.g., boiler repair, cleaning)",
    popularCategories: "Popular Services",
    searchBtn: "Search",
    hourlyRate: "Hourly rate",
    viewProfile: "View Profile",
    makeOffer: "Order Now",
    myOffers: "My Orders",
    becomePro: "Join as Pro",
    login: "Login",
    home: "Home",
    azn: "AZN",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    nameLabel: "Full Name",
    bioLabel: "Professional Bio",
    professionLabel: "Your Profession",
    avatarLabel: "Profile Picture",
    hourlyRateLabel: "Hourly Rate (10-100 AZN)",
    successUpdate: "Profile updated successfully!",
    cancel: "Cancel",
    loginBtn: "Login",
    signupBtn: "Create Account",
    emailLabel: "Email address",
    passwordLabel: "Password",
    authTitleLogin: "Welcome Back",
    authTitleSignup: "Join Helper.az",
    selectAccountType: "Select account type",
    customerRole: "Customer",
    proRole: "Professional",
    noAccount: "Don't have an account?",
    hasAccount: "Already a member?",
    panel: "Dashboard",
    incomingOffers: "New Bookings",
    myRequests: "My Orders",
    status: "Status",
    locationLabel: "Address",
    jobDesc: "Job Description",
    dateLabel: "Date",
    timeLabel: "Time",
    addressLabel: "Exact Address",
    noActivity: "No activity yet.",
    noProsFound: "No results found",
    noProsFoundSub: "Try different keywords or categories.",
    geminiSearching: "AI is finding experts...",
    send: "Send Request",
    security: "Security",
    details: "Details",
    accept: "Accept",
    decline: "Decline",
    verifyEmailTitle: "Verify Email",
    verifyEmailDesc: "Please check your inbox and click the link to verify your account.",
    onboardingTitle: "Complete Your Profile",
    onboardingStep1: "Photo",
    onboardingStep2: "Details",
    completeOnboarding: "Launch Profile",
    uploadPhoto: "Select Photo",
    bioMinLength: "Write a bit about your experience",
    photoRequired: "A photo is required for professionals",
    cityLabel: "City",
    next: "Continue",
    activeJobs: "Active & Pending",
    completedJobs: "Completed",
    profileViews: "Profile Views",
    quickActions: "Quick Actions",
    availabilityText: "Currently accepting orders",
    notAvailableText: "Busy / Not accepting orders",
    otherProfession: "Other (Please specify)",
    refresh: "Refresh",
    pending: "Pending",
    accepted: "Accepted",
    declined: "Declined",
    completed: "Completed",
    pay: "Make Payment",
    paid: "Paid",
    checkoutTitle: "Secure Checkout",
    cardNumber: "Card Number",
    expiry: "MM/YY",
    cvc: "CVC",
    payNow: "Pay Now",
    secureCheckout: "Bank-level security",
    paymentSuccess: "Payment successful!",
    summary: "Summary",
    serviceFee: "Service Fee",
    totalAmount: "Total Amount",
    verified: "Verified",
    unverified: "Unverified",
    securityAudit: "Security Audit",
    pciCompliance: "PCI Compliance",
    pciDesc: "Your card data is never stored on Helper.az servers.",
    safetyGuarantee: "100% Safety Guarantee",
    safetyDesc: "Our professionals undergo a rigorous background check.",
    howItWorks: "How it works?",
    whyUs: "Why us?",
    contact: "Contact",
    step1Title: "Search for Service",
    step1Desc: "Easily find what you need with our AI-powered search.",
    step2Title: "Select a Pro",
    step2Desc: "Review ratings and profiles to find your perfect match.",
    step3Title: "Secure Payment",
    step3Desc: "Pay safely through our platform after job completion.",
    whyUs1Title: "Verified Pros",
    whyUs1Desc: "Every professional is background checked for safety.",
    whyUs2Title: "Fixed Pricing",
    whyUs2Desc: "Know the price upfront with no hidden costs.",
    whyUs3Title: "24/7 Support",
    whyUs3Desc: "Our team is here to help you anytime, anywhere.",
    contactTitle: "Contact Us",
    contactSubtitle: "Have questions? Reach out to our team.",
    sendMessage: "Send Message",
    messageLabel: "Your Message",
    footerAbout: "Helper.az is the most trusted service marketplace in Baku.",
    rights: "All rights reserved.",
    // New
    emailVerifiedTitle: "Email Verified!",
    emailVerifiedDesc: "Congratulations! Your account has been successfully activated. You can now log in and start using our services.",
    goToLogin: "Go to Login"
  },
  ru: {
    heroTitle: "Профессиональные помощники",
    heroSubtitle: "Лучшие мастера Баку на одной платформе. Гарантия качества и безопасности.",
    searchPlaceholder: "Какая услуга вам нужна? (напр: ремонт котла, уборка)",
    popularCategories: "Популярные Услуги",
    searchBtn: "Поиск",
    hourlyRate: "Почасовая ставка",
    viewProfile: "Профиль",
    makeOffer: "Заказать",
    myOffers: "Мои заказы",
    becomePro: "Стать мастером",
    login: "Войти",
    home: "Главная",
    azn: "AZN",
    editProfile: "Редактировать",
    saveChanges: "Сохранить",
    nameLabel: "Имя и Фамилия",
    bioLabel: "Профессиональная Биография",
    professionLabel: "Профессия",
    avatarLabel: "Фото профиля",
    hourlyRateLabel: "Ставка (10-100 AZN)",
    successUpdate: "Профиль обновлен!",
    cancel: "Отмена",
    loginBtn: "Войти",
    signupBtn: "Регистрация",
    emailLabel: "Эл. почта",
    passwordLabel: "Пароль",
    authTitleLogin: "С возвращением",
    authTitleSignup: "Присоединиться",
    selectAccountType: "Выберите тип аккаунта",
    customerRole: "Клиент",
    proRole: "Мастер",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже зарегистрированы?",
    panel: "Панель управления",
    incomingOffers: "Новые заказы",
    myRequests: "Мои заказы",
    status: "Status",
    locationLabel: "Адрес",
    jobDesc: "Описание работы",
    dateLabel: "Дата",
    timeLabel: "Время",
    addressLabel: "Точный адрес",
    noActivity: "Активности пока нет.",
    noProsFound: "Ничего не найдено",
    noProsFoundSub: "Попробуйте изменить запрос.",
    geminiSearching: "AI ищет мастеров...",
    send: "Отправить заказ",
    security: "Безопасность",
    details: "Детали",
    accept: "Принять",
    decline: "Отказать",
    verifyEmailTitle: "Подтвердите Email",
    verifyEmailDesc: "Пожалуйста, проверьте почту для подтверждения аккаунта.",
    onboardingTitle: "Настройте профиль",
    onboardingStep1: "Фото",
    onboardingStep2: "Данные",
    completeOnboarding: "Открыть профиль",
    uploadPhoto: "Выбрать фото",
    bioMinLength: "Напишите немного о своем опыте",
    photoRequired: "Фото обязательно для мастеров",
    cityLabel: "Город",
    next: "Продолжить",
    activeJobs: "Активные и Ожидание",
    completedJobs: "Завершено",
    profileViews: "Просмотры",
    quickActions: "Действия",
    availabilityText: "Принимаю заказы",
    notAvailableText: "Занят / Не принимаю заказы",
    otherProfession: "Другое (Пожалуйста, уточните)",
    refresh: "Обновить",
    pending: "Ожидание",
    accepted: "Принято",
    declined: "Отклонено",
    completed: "Завершено",
    pay: "Оплатить",
    paid: "Оплачено",
    checkoutTitle: "Безопасная оплата",
    cardNumber: "Номер карты",
    expiry: "ММ/ГГ",
    cvc: "CVC",
    payNow: "Оплатить сейчас",
    secureCheckout: "Безопасность банковского уровня",
    paymentSuccess: "Оплата прошла успешно!",
    summary: "Итог",
    serviceFee: "Сервисный сбор",
    totalAmount: "Итоговая сумма",
    verified: "Проверено",
    unverified: "Не проверено",
    securityAudit: "Аудит безопасности",
    pciCompliance: "Соответствие PCI",
    pciDesc: "Данные вашей карты не хранятся на серверах Helper.az.",
    safetyGuarantee: "100% Гарантия безопасности",
    safetyDesc: "Наши специалисты проходят строгую проверку анкетных данных.",
    howItWorks: "Как это работает?",
    whyUs: "Почему мы?",
    contact: "Контакты",
    step1Title: "Поиск Услуги",
    step1Desc: "Легко найдите мастера с помощью нашего AI-поиска.",
    step2Title: "Выберите Мастера",
    step2Desc: "Изучите профили и отзывы, чтобы найти лучшего мастера.",
    step3Title: "Безопасная Оплата",
    step3Desc: "Платите безопасно через платформу после завершения работы.",
    whyUs1Title: "Проверенные Мастера",
    whyUs1Desc: "Каждый мастер проходит проверку личности.",
    whyUs2Title: "Фиксированные Цены",
    whyUs2Desc: "Цена известна заранее, без скрытых комиссий.",
    whyUs3Title: "24/7 Поддержка",
    whyUs3Desc: "Наша команда всегда готова помочь вам.",
    contactTitle: "Связаться с Нами",
    contactSubtitle: "Есть вопросы? Напишите нам.",
    sendMessage: "Отправить сообщение",
    messageLabel: "Ваше сообщение",
    footerAbout: "Helper.az — самый надежный маркетплейс услуг в Баку.",
    rights: "Все права защищены.",
    // New
    emailVerifiedTitle: "Email Подтвержден!",
    emailVerifiedDesc: "Поздравляем! Ваш аккаунт успешно активирован. Теперь вы можете войти и начать пользоваться нашими услугами.",
    goToLogin: "Перейти к Входу"
  }
};
