
import React from 'react';
import { Profile, Language } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'p1',
    name: 'Elvin Məmmədov',
    role: 'PROFESSIONAL',
    profession: 'Santexnik',
    skills: ['Santexnik', 'Təmir', 'Boru təmiri'],
    bio: '10 ildən çox təcrübəli santexnik ustasıyam. Hər növ boru və kran təmirini yüksək keyfiyyətlə yerinə yetirirəm.',
    hourlyRate: 25,
    rating: 4.8,
    reviewsCount: 42,
    avatar: 'https://images.unsplash.com/photo-1540560340339-44432095813d?auto=format&fit=crop&q=80&w=200&h=200',
    location: 'Bakı, Nərimanov',
    availability: ['Bazar ertəsi', 'Çərşənbə', 'Cümə'],
    joinedDate: '2023-01-15',
    onboarding_completed: true
  }
];

export const I18N = {
  az: {
    heroTitle: "Eviniz üçün peşəkar köməkçilər",
    heroSubtitle: "Bakının ən yaxşı ustaları bir platformada. Təhlükəsiz ödəniş və zəmanətli xidmət.",
    searchPlaceholder: "Hansı xidmətə ehtiyacınız var? (məs: kombi təmiri, təmizlik)",
    popularCategories: "Populyar Xidmətlər",
    plumbing: "Santexnika",
    cleaning: "Təmizlik",
    electrician: "Elektrik",
    renovation: "Təmir",
    searchBtn: "Axtar",
    hourlyRate: "Saatlıq tarif",
    viewProfile: "Profilə bax",
    makeOffer: "Sifariş et",
    myOffers: "Sifarişlərim",
    becomePro: "Usta ol",
    login: "Daxil ol",
    home: "Ana səhifə",
    azn: "AZN",
    editProfile: "Profili redaktə et",
    saveChanges: "Yadda saxla",
    nameLabel: "Ad və Soyad",
    bioLabel: "Peşəkar Bioqrafiya",
    professionLabel: "Peşəniz",
    avatarLabel: "Profil şəkli (URL)",
    hourlyRateLabel: "Saatlıq tarif (10-100 AZN)",
    successUpdate: "Profil uğurla yeniləndi!",
    cancel: "Ləğv et",
    loginBtn: "Daxil ol",
    signupBtn: "Qeydiyyatdan keç",
    emailLabel: "E-poçt ünvanı",
    passwordLabel: "Şifrə",
    authTitleLogin: "Xoş gəlmisiniz",
    authTitleSignup: "Platformaya qoşulun",
    selectAccountType: "Hesab növünü seçin",
    customerRole: "Müştəri",
    proRole: "Usta",
    noAccount: "Hesabınız yoxdur?",
    hasAccount: "Artıq qeydiyyatdan keçmisiniz?",
    panel: "İdarə Paneli",
    incomingOffers: "Yeni Sifarişlər",
    myRequests: "Mənim Sifarişlərim",
    status: "Status",
    locationLabel: "Ünvan",
    jobDesc: "İşin təsviri",
    dateLabel: "Tarix",
    timeLabel: "Vaxt",
    addressLabel: "Tam ünvan",
    noActivity: "Hələ ki heç bir fəaliyyət yoxdur.",
    noProsFound: "Nəticə tapılmadı",
    noProsFoundSub: "Axtarış sözlərini dəyişərək yenidən yoxlayın.",
    geminiSearching: "AI mütəxəssis axtarır...",
    send: "Sifarişi göndər",
    security: "Təhlükəsizlik",
    details: "Detallar",
    accept: "Qəbul et",
    decline: "İmtina et",
    verifyEmailTitle: "E-poçtu təsdiqləyin",
    verifyEmailDesc: "Qeydiyyatı tamamlamaq üçün e-poçtunuza göndərilən linkə keçid edin.",
    onboardingTitle: "Profilinizi tamamlayın",
    onboardingStep1: "Şəkil",
    onboardingStep2: "Detallar",
    completeOnboarding: "Profilimi aç",
    uploadPhoto: "Şəkil yüklə",
    bioMinLength: "Təcrübəniz haqqında ən azı 50 simvol yazın",
    photoRequired: "Usta olmaq üçün real şəkil mütləqdir",
    cityLabel: "Şəhər",
    next: "Davam et",
    activeJobs: "Aktiv İşlər",
    completedJobs: "Tamamlananlar",
    profileViews: "Baxış sayı",
    quickActions: "Sürətli Əməliyyatlar",
    availabilityText: "Hal-hazırda sifariş qəbul edirəm",
    notAvailableText: "Məşğulam / Sifariş qəbul edilmir"
  },
  en: {
    heroTitle: "Professional Helpers for Your Home",
    heroSubtitle: "Top experts in Baku on one platform. Secure payments and guaranteed service.",
    searchPlaceholder: "What service do you need? (e.g., boiler repair, cleaning)",
    popularCategories: "Popular Services",
    plumbing: "Plumbing",
    cleaning: "Cleaning",
    electrician: "Electrician",
    renovation: "Renovation",
    searchBtn: "Search",
    hourlyRate: "Hourly rate",
    viewProfile: "View Profile",
    makeOffer: "Order Now",
    myOffers: "My Orders",
    becomePro: "Join as Pro",
    login: "Login",
    home: "Home",
    azn: "AZN",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    nameLabel: "Full Name",
    bioLabel: "Professional Bio",
    professionLabel: "Your Profession",
    avatarLabel: "Profile Picture (URL)",
    hourlyRateLabel: "Hourly Rate (10-100 AZN)",
    successUpdate: "Profile updated successfully!",
    cancel: "Cancel",
    loginBtn: "Login",
    signupBtn: "Create Account",
    emailLabel: "Email address",
    passwordLabel: "Password",
    authTitleLogin: "Welcome Back",
    authTitleSignup: "Join Helper.az",
    selectAccountType: "Select account type",
    customerRole: "Customer",
    proRole: "Professional",
    noAccount: "Don't have an account?",
    hasAccount: "Already a member?",
    panel: "Dashboard",
    incomingOffers: "New Bookings",
    myRequests: "My Orders",
    status: "Status",
    locationLabel: "Address",
    jobDesc: "Job Description",
    dateLabel: "Date",
    timeLabel: "Time",
    addressLabel: "Exact Address",
    noActivity: "No activity yet.",
    noProsFound: "No results found",
    noProsFoundSub: "Try different keywords or categories.",
    geminiSearching: "AI is finding experts...",
    send: "Send Request",
    security: "Security",
    details: "Details",
    accept: "Accept",
    decline: "Decline",
    verifyEmailTitle: "Verify Email",
    verifyEmailDesc: "Please check your inbox and click the link to verify your account.",
    onboardingTitle: "Complete Your Profile",
    onboardingStep1: "Photo",
    onboardingStep2: "Details",
    completeOnboarding: "Launch Profile",
    uploadPhoto: "Upload Photo",
    bioMinLength: "Write at least 50 characters about your experience",
    photoRequired: "A real photo is required for professionals",
    cityLabel: "City",
    next: "Continue",
    activeJobs: "Active Jobs",
    completedJobs: "Completed",
    profileViews: "Profile Views",
    quickActions: "Quick Actions",
    availabilityText: "Currently accepting orders",
    notAvailableText: "Busy / Not accepting orders"
  },
  ru: {
    heroTitle: "Профессиональные помощники",
    heroSubtitle: "Лучшие мастера Баку на одной платформе. Гарантия качества и безопасности.",
    searchPlaceholder: "Какая услуга вам нужна? (напр: ремонт котла, уборка)",
    popularCategories: "Популярные Услуги",
    plumbing: "Сантехника",
    cleaning: "Уборка",
    electrician: "Электрик",
    renovation: "Ремонт",
    searchBtn: "Поиск",
    hourlyRate: "Почасовая ставка",
    viewProfile: "Профиль",
    makeOffer: "Заказать",
    myOffers: "Мои заказы",
    becomePro: "Стать мастером",
    login: "Войти",
    home: "Главная",
    azn: "AZN",
    editProfile: "Редактировать",
    saveChanges: "Сохранить",
    nameLabel: "Имя и Фамилия",
    bioLabel: "Профессиональная Биография",
    professionLabel: "Профессия",
    avatarLabel: "Фото профиля (URL)",
    hourlyRateLabel: "Ставка (10-100 AZN)",
    successUpdate: "Профиль обновлен!",
    cancel: "Отмена",
    loginBtn: "Войти",
    signupBtn: "Регистрация",
    emailLabel: "Эл. почта",
    passwordLabel: "Пароль",
    authTitleLogin: "С возвращением",
    authTitleSignup: "Присоединиться",
    selectAccountType: "Выберите тип аккаунта",
    customerRole: "Клиент",
    proRole: "Мастер",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже зарегистрированы?",
    panel: "Панель управления",
    incomingOffers: "Новые заказы",
    myRequests: "Мои заказы",
    status: "Статус",
    locationLabel: "Адрес",
    jobDesc: "Описание работы",
    dateLabel: "Дата",
    timeLabel: "Время",
    addressLabel: "Точный адрес",
    noActivity: "Активности пока нет.",
    noProsFound: "Ничего не найдено",
    noProsFoundSub: "Попробуйте изменить запрос.",
    geminiSearching: "AI ищет мастеров...",
    send: "Отправить заказ",
    security: "Безопасность",
    details: "Детали",
    accept: "Принять",
    decline: "Отказать",
    verifyEmailTitle: "Подтвердите Email",
    verifyEmailDesc: "Пожалуйста, проверьте почту для подтверждения аккаунта.",
    onboardingTitle: "Настройте профиль",
    onboardingStep1: "Фото",
    onboardingStep2: "Данные",
    completeOnboarding: "Открыть профиль",
    uploadPhoto: "Загрузить фото",
    bioMinLength: "Минимум 50 символов о вашем опыте",
    photoRequired: "Фото обязательно для мастеров",
    cityLabel: "Город",
    next: "Продолжить",
    activeJobs: "Активные заказы",
    completedJobs: "Завершено",
    profileViews: "Просмотры",
    quickActions: "Действия",
    availabilityText: "Принимаю заказы",
    notAvailableText: "Занят / Не принимаю заказы"
  }
};
